apiVersion: apps/v1
kind: Deployment
metadata:
  name: construction-app-dev
  labels:
    app: construction-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: construction-app-dev
  template:
    metadata:
      labels:
        app: construction-app-dev
    spec:
      containers:
        - name: construction-app
          image: construction-app
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: construction-secrets
                  key: mongodb-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: construction-secrets
                  key: jwt-secret
          command: ["npm", "run", "dev"]
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=200"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {} 