apiVersion: v1
kind: Secret
metadata:
  name: construction-secrets
  labels:
    app: construction-app
type: Opaque
stringData:
  mongodb-uri: "mongodb://root:password@mongodb-service:27017/construction_management?authSource=admin"
  jwt-secret: "your-jwt-secret-key-replace-with-actual-secret" 