apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
- ../../base
- ../../../kubernetes/deployment.yaml
- ../../../kubernetes/ingress.yaml

commonLabels:
  environment: production 